### ISSUE TITLE
Viewer cant handle some IPS's

### ISSUE THREAD

**Issue by jkiddo** [jddamore/IPSviewer#15]
<img width="477" alt="image" src="https://github.com/jddamore/IPSviewer/assets/211696/9bb71961-5628-43a3-940e-c1441082be7d">
[ips.json](https://github.com/jddamore/IPSviewer/files/12920468/ips.json)
 -error is reproduceable with the attached IPS.

**Comment by jddamore** [comment]
Jens, 

So I didn't see the error from your screenshot, but in the sample you posted, there are a few issues: 

1) https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Bundle-uv-ips.html
The fullUrls were missing but are required by standard. The IPS viewer uses those to crosslink entries

2) The sample had some sections with no data

3) The sample had what appeared to be "Immunization" resource in the Allergies section. 

4) You reference the Medications in the section for Medications (but better to just reference the MedicationStatements as guided here: https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Composition-uv-ips-definitions.html#diff_Composition.section:sectionMedications

I went ahead and attempted to "fix" the four above issues. For the sections with no data, I just removed them. The new sample is posted here: https://github.com/jddamore/IPSviewer/blob/main/samples/connectathon_samples/DK_Jens_Villadsen_02.json

That sample will render with no edits to viewer. There might be some improvements to make, which we can discuss here. It will tell you some requried sections are missing and that you have missing references (your sample didn't contian the referenced Immunization resource). Let me know if you have another sample with the "includes" error as you screenshot above.

**Comment by jkiddo** [comment]
Thx for the response. I fixed 1) and it did the job. 2) I can live with. 3) is now fixed - thx. 4) I dont entirely follow you. I've added both MedicationStatements and Medications. From https://build.fhir.org/ig/HL7/fhir-ips/ipsStructure.html#list-of-profiles it looks like both should be there. Do you suggest that I remove the Medications from the section and just have them referenced from the MedicationStatement.medication?.

**Comment by jddamore** [comment]
Just reference the Medication resources from the MedicationStatement. Don't include "Medication" resources in the Composition.section.entry for the medications section since it's not in the definition of expected resource profiles (i.e. Reference(MedicationStatement, MedicationRequest, MedicationAdministration, MedicationDispense, DocumentReference from that link)

**Comment by jkiddo** [comment]
<img width="1036" alt="image" src="https://github.com/jddamore/IPSviewer/assets/211696/6a0ed4ea-fbbf-43ec-aa44-a555fe5691db">

**Comment by jkiddo** [comment]
One could get the idea that if its mentioned there, then it should be part of the section

**Comment by jkiddo** [comment]
The text could be understood so:

> Following are the profiles that have been defined for each section. (R) denotes a required section (i.e. must be present in an IPS), (S) denotes a recommended section, the others are optional

**Comment by jddamore** [comment]
I agree that's confusing. I opened a JIRA to change that wording: https://jira.hl7.org/browse/FHIR-42937 Comment there for change to standard. That said, add more here if the viewer isn't working (or needs improvement) as you dig further.

**Comment by jkiddo** [comment]
👍
